function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildChatHtml({ projectName, projectDir }) {
  const safeName = escapeHtml(projectName);
  const safeDir = escapeHtml(projectDir);
  return [
    "<!doctype html>",
    "<html lang=\"en\">",
    "<head>",
    "  <meta charset=\"utf-8\">",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
    "  <title>KFC Chat</title>",
    "  <link rel=\"stylesheet\" href=\"/assets/kfc-chat.css\">",
    "</head>",
    "<body>",
    "  <div class=\"app-shell\">",
    "    <header class=\"hero\">",
    "      <div>",
    "        <p class=\"eyebrow\">KFC Chat</p>",
    "        <h1>Bound Codex Session Chat</h1>",
    "        <p class=\"lede\">Resume one bound Codex session per project through a guarded browser surface. Transcript truth stays in Codex; KFC mirrors local chat state for speed and continuity.</p>",
    "      </div>",
    `      <div class="hero-meta"><span class="meta-chip">Project</span><code>${safeName}</code><small>${safeDir}</small></div>`,
    "    </header>",
    "",
    "    <main class=\"workspace\">",
    "      <section class=\"panel panel-transcript\">",
    "        <div class=\"panel-head transcript-head\">",
    "          <div>",
    "            <p class=\"panel-kicker\">Conversation</p>",
    "            <h2>Bound Session Timeline</h2>",
    "          </div>",
    "          <span id=\"session-status-chip\" class=\"meta-chip\">Idle</span>",
    "        </div>",
    "        <section class=\"conversation-summary\">",
    "          <div class=\"summary-card\">",
    "            <span class=\"summary-label\">Session</span>",
    "            <strong id=\"summary-session-id\">Unbound</strong>",
    "            <small id=\"summary-session-note\">Bind a Codex session to start the chat.</small>",
    "          </div>",
    "          <div class=\"summary-card\">",
    "            <span class=\"summary-label\">Connection</span>",
    "            <strong id=\"summary-connection\">Disconnected</strong>",
    "            <small id=\"summary-queue\">Queue: 0</small>",
    "          </div>",
    "        </section>",
    "        <section class=\"auth-card\">",
    "          <label class=\"field\">",
    "            <span>Token</span>",
    "            <input id=\"token-input\" type=\"password\" placeholder=\"Paste the chat token\" autocomplete=\"off\">",
    "          </label>",
    "          <div class=\"auth-actions\">",
    "            <button id=\"connect-button\" type=\"button\">Connect</button>",
    "            <button id=\"disconnect-button\" type=\"button\" class=\"button-secondary\">Disconnect</button>",
    "          </div>",
    "        </section>",
    "        <div id=\"transcript-list\" class=\"transcript-list\"></div>",
    "        <section class=\"composer\">",
    "          <label class=\"field\">",
    "            <span>Next Prompt</span>",
    "            <textarea id=\"prompt-input\" rows=\"5\" placeholder=\"Send the next prompt into the bound Codex session.\"></textarea>",
    "          </label>",
    "          <div class=\"composer-actions\">",
    "            <span id=\"queue-indicator\" class=\"hint\">Queue: 0</span>",
    "            <button id=\"send-button\" type=\"button\">Send Prompt</button>",
    "          </div>",
    "        </section>",
    "      </section>",
    "",
    "      <section class=\"panel panel-session\">",
    "        <div class=\"panel-head\">",
    "          <div>",
    "            <p class=\"panel-kicker\">Bound Session</p>",
    "            <h2 id=\"bound-session-title\">No Codex session bound</h2>",
    "          </div>",
    "          <span id=\"bound-state-chip\" class=\"meta-chip\">Blocked</span>",
    "        </div>",
    "        <dl id=\"bound-session-grid\" class=\"detail-grid\"></dl>",
    "        <section class=\"action-card\">",
    "          <div class=\"section-row\">",
    "            <h3>Manual Interactive Resume</h3>",
    "            <button id=\"copy-resume-button\" type=\"button\" class=\"button-secondary\">Copy Command</button>",
    "          </div>",
    "          <p class=\"hint\">Terminal-style interactive resume is outside this v1 browser surface. Use the command below when you want to continue the same session directly in Codex.</p>",
    "          <pre id=\"manual-resume-command\" class=\"command-block\">No Codex session bound.</pre>",
    "        </section>",
    "        <section class=\"action-card\">",
    "          <div class=\"section-row\">",
    "            <h3>Light Session Actions</h3>",
    "          </div>",
    "          <div class=\"quick-actions\">",
    "            <button id=\"copy-session-id-button\" type=\"button\" class=\"button-secondary\">Copy Session ID</button>",
    "            <button id=\"copy-session-path-button\" type=\"button\" class=\"button-secondary\">Copy Session Path</button>",
    "            <button id=\"reveal-session-file-button\" type=\"button\" class=\"button-secondary\">Reveal File</button>",
    "            <button id=\"reveal-session-folder-button\" type=\"button\" class=\"button-secondary\">Reveal Folder</button>",
    "          </div>",
    "          <p class=\"hint\">These actions stay project-bound. Session browsing and switching remain in <code>kfc-session</code>.</p>",
    "        </section>",
    "        <section class=\"action-card\">",
    "          <h3>Live State</h3>",
    "          <ul id=\"live-state-list\" class=\"state-list\"></ul>",
    "        </section>",
    "      </section>",
    "    </main>",
    "",
    "    <footer class=\"footer\">",
    "      <span id=\"status-line\">Ready.</span>",
    "    </footer>",
    "  </div>",
    "  <script src=\"/assets/kfc-chat.js\"></script>",
    "</body>",
    "</html>"
  ].join("\n");
}

export const KFC_CHAT_CSS = [
  ":root {",
  "  color-scheme: light dark;",
  "  --bg: #f6f1eb;",
  "  --bg-accent: #ebdfd3;",
  "  --panel: rgba(255, 250, 243, 0.92);",
  "  --panel-soft: rgba(255, 255, 255, 0.36);",
  "  --panel-strong: rgba(255, 255, 255, 0.72);",
  "  --border: rgba(94, 76, 55, 0.2);",
  "  --text: #24190f;",
  "  --muted: #6d5a48;",
  "  --accent: #15616d;",
  "  --accent-soft: rgba(21, 97, 109, 0.12);",
  "  --accent-strong: #0f4d56;",
  "  --highlight: #c06a41;",
  "  --shadow: rgba(61, 42, 24, 0.12);",
  "  --user-bubble: #e8f2f4;",
  "  --assistant-bubble: #fff5ec;",
  "  --system-bubble: rgba(44, 61, 78, 0.06);",
  "  font-family: \"Segoe UI Variable\", \"Aptos\", system-ui, sans-serif;",
  "}",
  "@media (prefers-color-scheme: dark) {",
  "  :root {",
  "    --bg: #0f171e;",
  "    --bg-accent: #16232f;",
  "    --panel: rgba(18, 24, 32, 0.94);",
  "    --panel-soft: rgba(255, 255, 255, 0.04);",
  "    --panel-strong: rgba(255, 255, 255, 0.08);",
  "    --border: rgba(148, 181, 207, 0.18);",
  "    --text: #edf4fb;",
  "    --muted: #9bb0c3;",
  "    --accent: #7ad0d8;",
  "    --accent-soft: rgba(122, 208, 216, 0.14);",
  "    --accent-strong: #b6ebef;",
  "    --highlight: #e4a06d;",
  "    --shadow: rgba(0, 0, 0, 0.28);",
  "    --user-bubble: rgba(21, 97, 109, 0.22);",
  "    --assistant-bubble: rgba(192, 106, 65, 0.18);",
  "    --system-bubble: rgba(255, 255, 255, 0.06);",
  "  }",
  "}",
  "* { box-sizing: border-box; }",
  "body { margin: 0; background: radial-gradient(circle at top, var(--bg-accent), var(--bg) 42%); color: var(--text); }",
  "button, input, textarea { font: inherit; }",
  "code, pre, textarea { font-family: \"Cascadia Code\", \"Consolas\", monospace; }",
  ".app-shell { max-width: 1440px; margin: 0 auto; padding: 24px; display: grid; gap: 20px; }",
  ".hero { display: flex; align-items: flex-start; justify-content: space-between; gap: 20px; }",
  ".eyebrow, .panel-kicker { margin: 0 0 6px; color: var(--highlight); text-transform: uppercase; letter-spacing: 0.08em; font-size: 12px; font-weight: 700; }",
  ".hero h1, .panel-head h2, .action-card h3, .summary-card strong { margin: 0; }",
  ".lede, .hint, .summary-card small { color: var(--muted); max-width: 72ch; margin: 8px 0 0; }",
  ".hero-meta { display: grid; gap: 8px; justify-items: end; text-align: right; }",
  ".hero-meta small { color: var(--muted); }",
  ".meta-chip { display: inline-flex; align-items: center; gap: 8px; border-radius: 999px; border: 1px solid var(--border); background: var(--accent-soft); color: var(--accent); padding: 6px 10px; font-size: 12px; font-weight: 600; }",
  ".workspace { display: grid; grid-template-columns: minmax(0, 1.25fr) minmax(320px, 0.75fr); gap: 20px; }",
  ".panel, .action-card, .auth-card, .summary-card { background: var(--panel); border: 1px solid var(--border); border-radius: 24px; box-shadow: 0 16px 36px var(--shadow); }",
  ".panel { padding: 20px; display: grid; gap: 16px; min-height: 0; }",
  ".panel-transcript { gap: 14px; }",
  ".panel-session { gap: 14px; background: color-mix(in srgb, var(--panel) 92%, transparent); }",
  ".panel-head, .section-row, .composer-actions, .auth-actions, .transcript-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; }",
  ".conversation-summary { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; }",
  ".summary-card { padding: 14px 16px; background: var(--panel-soft); box-shadow: none; }",
  ".summary-label { display: inline-block; color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 6px; }",
  ".field { display: grid; gap: 8px; }",
  ".field span { color: var(--muted); font-size: 13px; }",
  "input, textarea { border-radius: 14px; border: 1px solid var(--border); padding: 12px 14px; background: var(--panel-strong); color: var(--text); width: 100%; }",
  "textarea { resize: vertical; min-height: 140px; }",
  "button { border-radius: 14px; border: 1px solid color-mix(in srgb, var(--accent) 52%, var(--border)); background: color-mix(in srgb, var(--accent) 12%, transparent); color: var(--text); padding: 12px 14px; cursor: pointer; }",
  "button:disabled { opacity: 0.55; cursor: not-allowed; }",
  ".button-secondary { border-color: var(--border); background: transparent; }",
  ".auth-card, .action-card { padding: 16px; display: grid; gap: 12px; box-shadow: none; background: var(--panel-soft); }",
  ".quick-actions { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; }",
  ".transcript-list { display: grid; gap: 14px; max-height: 66vh; overflow: auto; padding-right: 6px; align-content: start; }",
  ".message-group { display: grid; gap: 6px; max-width: min(72ch, 100%); }",
  ".message-group[data-align=\"right\"] { justify-self: end; }",
  ".message-group[data-align=\"left\"] { justify-self: start; }",
  ".message-group-head { display: flex; align-items: center; gap: 8px; color: var(--muted); font-size: 12px; }",
  ".message-role { text-transform: uppercase; letter-spacing: 0.08em; font-weight: 700; }",
  ".message-status { display: inline-flex; align-items: center; border-radius: 999px; padding: 2px 8px; border: 1px solid var(--border); background: var(--panel-strong); }",
  ".message-group-body { display: grid; gap: 3px; }",
  ".message-bubble { padding: 12px 14px; border: 1px solid var(--border); background: var(--assistant-bubble); line-height: 1.45; box-shadow: 0 8px 18px rgba(0, 0, 0, 0.04); }",
  ".message-group[data-role=\"user\"] .message-bubble { background: var(--user-bubble); border-color: color-mix(in srgb, var(--accent) 36%, var(--border)); }",
  ".message-group[data-role=\"assistant\"] .message-bubble, .message-group[data-role=\"codex_result\"] .message-bubble, .message-group[data-role=\"codex_tail\"] .message-bubble { background: var(--assistant-bubble); }",
  ".message-bubble[data-shape=\"single\"] { border-radius: 20px; }",
  ".message-bubble[data-shape=\"top\"] { border-radius: 20px 20px 10px 10px; }",
  ".message-bubble[data-shape=\"middle\"] { border-radius: 10px; }",
  ".message-bubble[data-shape=\"bottom\"] { border-radius: 10px 10px 20px 20px; }",
  ".message-group[data-align=\"right\"] .message-bubble[data-shape=\"single\"] { border-radius: 20px 20px 6px 20px; }",
  ".message-group[data-align=\"right\"] .message-bubble[data-shape=\"top\"] { border-radius: 20px 20px 10px 20px; }",
  ".message-group[data-align=\"right\"] .message-bubble[data-shape=\"bottom\"] { border-radius: 10px 20px 20px 20px; }",
  ".message-group[data-align=\"left\"] .message-bubble[data-shape=\"single\"] { border-radius: 20px 20px 20px 6px; }",
  ".message-group[data-align=\"left\"] .message-bubble[data-shape=\"top\"] { border-radius: 20px 20px 20px 10px; }",
  ".message-group[data-align=\"left\"] .message-bubble[data-shape=\"bottom\"] { border-radius: 20px 10px 20px 20px; }",
  ".transcript-event { justify-self: center; max-width: min(64ch, 100%); width: 100%; display: grid; gap: 6px; padding: 10px 14px; border-radius: 16px; border: 1px dashed var(--border); background: var(--system-bubble); color: var(--muted); text-align: center; }",
  ".transcript-event strong { color: var(--text); font-size: 13px; }",
  ".transcript-empty { justify-self: center; width: 100%; max-width: min(64ch, 100%); display: grid; gap: 6px; padding: 18px 20px; border-radius: 18px; border: 1px dashed var(--border); background: var(--system-bubble); text-align: center; color: var(--muted); }",
  ".transcript-empty strong { color: var(--text); }",
  ".detail-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; margin: 0; }",
  ".detail-grid div { border: 1px solid var(--border); border-radius: 18px; padding: 12px; background: var(--panel-soft); }",
  ".detail-grid dt { color: var(--muted); font-size: 12px; margin-bottom: 6px; }",
  ".detail-grid dd { margin: 0; word-break: break-word; }",
  ".command-block { margin: 0; white-space: pre-wrap; background: color-mix(in srgb, var(--panel) 88%, black 4%); border: 1px solid var(--border); border-radius: 16px; padding: 12px; }",
  ".state-list { margin: 0; padding-left: 18px; color: var(--muted); display: grid; gap: 8px; }",
  ".footer { color: var(--muted); font-size: 14px; }",
  "@media (max-width: 1040px) { .workspace { grid-template-columns: 1fr; } .hero { flex-direction: column; } .hero-meta { justify-items: start; text-align: left; } }",
  "@media (max-width: 760px) { .conversation-summary, .detail-grid, .quick-actions { grid-template-columns: 1fr; } .app-shell { padding: 16px; } .composer-actions, .auth-actions, .panel-head, .section-row { flex-direction: column; align-items: stretch; } .message-group { max-width: 100%; } }",
  ""
].join("\n");

export const KFC_CHAT_JS = [
  "const state = { token: '', session: null, transcript: [], ws: null, connected: false };",
  "const byId = (id) => document.getElementById(id);",
  "",
  "function escapeHtml(value) {",
  "  return String(value || '')",
  "    .replace(/&/g, '&amp;')",
  "    .replace(/</g, '&lt;')",
  "    .replace(/>/g, '&gt;')",
  "    .replace(/\\\"/g, '&quot;');",
  "}",
  "",
  "function setStatus(text) { byId('status-line').textContent = text; }",
  "",
  "async function copyText(text, successMessage) {",
  "  if (!text) {",
  "    setStatus('Nothing to copy.');",
  "    return;",
  "  }",
  "  try {",
  "    await navigator.clipboard.writeText(text);",
  "    setStatus(successMessage);",
  "  } catch (err) {",
  "    setStatus(err instanceof Error ? err.message : String(err));",
  "  }",
  "}",
  "",
  "function tokenStorageKey() {",
  "  return `kfc-chat.token.${location.pathname}`;",
  "}",
  "",
  "function bubbleShape(index, total) {",
  "  if (total === 1) return 'single';",
  "  if (index === 0) return 'top';",
  "  if (index === total - 1) return 'bottom';",
  "  return 'middle';",
  "}",
  "",
  "function renderSession() {",
  "  const session = state.session;",
  "  byId('session-status-chip').textContent = session?.status || 'idle';",
  "  byId('queue-indicator').textContent = `Queue: ${session?.queue_depth || 0}`;",
  "  byId('summary-connection').textContent = state.connected ? 'Connected' : 'Disconnected';",
  "  byId('summary-queue').textContent = `Queue: ${session?.queue_depth || 0}`;",
  "  const bound = session?.bound_session;",
  "  byId('bound-state-chip').textContent = bound?.bound ? 'Bound' : 'Blocked';",
  "  byId('bound-session-title').textContent = bound?.bound ? bound.session_id : 'No Codex session bound';",
  "  byId('summary-session-id').textContent = bound?.bound ? bound.session_id : 'Unbound';",
  "  byId('summary-session-note').textContent = bound?.bound",
  "    ? `Plan ${bound.plan_id}`",
  "    : 'Bind a Codex session to start the chat.';",
  "  byId('manual-resume-command').textContent = bound?.manual_resume_command || bound?.reason || 'No Codex session bound.';",
  "  const items = bound?.bound",
  "    ? [['Plan ID', bound.plan_id], ['Session ID', bound.session_id], ['Session Path', bound.session_path], ['Profile', bound.profile || '<none>'], ['Bound At', bound.bound_at || '<unknown>'], ['Project Plan', bound.plan_path || '<unknown>']]",
  "    : [['State', bound?.reason || 'No Codex session bound.']];",
  "  byId('bound-session-grid').innerHTML = items.map(([label, value]) => `<div><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd></div>`).join('');",
  "  const liveState = [",
  "    `Status: ${session?.status || 'idle'}`,",
  "    `Busy: ${session?.busy ? 'yes' : 'no'}`,",
  "    `Queue depth: ${session?.queue_depth || 0}`,",
  "    `Connections: ${session?.connection_count || 0}`,",
  "    `Last prompt: ${session?.last_prompt_at || '<none>'}`,",
  "    `Last result: ${session?.last_result?.text || '<none>'}`",
  "  ];",
  "  byId('live-state-list').innerHTML = liveState.map((item) => `<li>${escapeHtml(item)}</li>`).join('');",
  "}",
  "",
  "function renderTranscript() {",
  "  const blocks = state.transcript || [];",
  "  if (blocks.length === 0) {",
  "    byId('transcript-list').innerHTML = '<article class=\"transcript-empty\"><strong>No conversation yet.</strong><div>Connect to the bound session and send the next prompt to start the chat timeline.</div></article>';",
  "    return;",
  "  }",
  "  byId('transcript-list').innerHTML = blocks.map((block) => {",
  "    if (block.type === 'event_row') {",
  "      return `<article class=\"transcript-event\"><strong>${escapeHtml(block.label || 'Event')}</strong><div>${escapeHtml(block.text || '')}</div><small>${escapeHtml(block.created_at || '')}${block.status ? ` • ${escapeHtml(block.status)}` : ''}</small></article>`;",
  "    }",
  "    const bubbles = (block.items || []).map((item, index) => `<div class=\"message-bubble\" data-shape=\"${bubbleShape(index, (block.items || []).length)}\">${escapeHtml(item.text || '')}</div>`).join('');",
  "    return `<article class=\"message-group\" data-role=\"${escapeHtml(block.role || 'assistant')}\" data-align=\"${escapeHtml(block.align || 'left')}\"><div class=\"message-group-head\"><span class=\"message-role\">${escapeHtml(block.label || 'Codex')}</span>${block.status ? `<span class=\"message-status\">${escapeHtml(block.status)}</span>` : ''}<span class=\"message-time\">${escapeHtml(block.created_at || '')}</span></div><div class=\"message-group-body\">${bubbles}</div></article>`;",
  "  }).join('');",
  "}",
  "",
  "async function fetchJson(url, options = {}) {",
  "  const response = await fetch(url, {",
  "    ...options,",
  "    headers: {",
  "      'Content-Type': 'application/json',",
  "      Authorization: state.token ? `Bearer ${state.token}` : '',",
  "      ...(options.headers || {})",
  "    }",
  "  });",
  "  const text = await response.text();",
  "  let payload = {};",
  "  try { payload = text ? JSON.parse(text) : {}; } catch { payload = { error: text || 'Invalid JSON response.' }; }",
  "  if (!response.ok) {",
  "    throw new Error(payload.error || `Request failed (${response.status})`);",
  "  }",
  "  return payload;",
  "}",
  "",
  "async function loadBootstrap() {",
  "  const [sessionPayload, transcriptPayload] = await Promise.all([",
  "    fetchJson('/api/chat/session'),",
  "    fetchJson('/api/chat/transcript')",
  "  ]);",
  "  state.session = sessionPayload;",
  "  state.transcript = transcriptPayload.items || [];",
  "  renderSession();",
  "  renderTranscript();",
  "}",
  "",
  "function disconnect() {",
  "  if (state.ws) {",
  "    state.ws.close();",
  "    state.ws = null;",
  "  }",
  "  state.connected = false;",
  "  if (state.session) renderSession();",
  "}",
  "",
  "function connectWebSocket() {",
  "  disconnect();",
  "  const protocol = location.protocol === 'https:' ? 'wss' : 'ws';",
  "  const ws = new WebSocket(`${protocol}://${location.host}/ws?token=${encodeURIComponent(state.token)}`);",
  "  state.ws = ws;",
  "  ws.addEventListener('open', () => {",
  "    state.connected = true;",
  "    renderSession();",
  "    setStatus('Connected to KFC Chat.');",
  "  });",
  "  ws.addEventListener('message', (event) => {",
  "    let packet;",
  "    try { packet = JSON.parse(String(event.data || '{}')); } catch { return; }",
  "    if (packet.type === 'bootstrap') {",
  "      state.session = packet.payload.session;",
  "      state.transcript = packet.payload.transcript || [];",
  "      renderSession();",
  "      renderTranscript();",
  "      return;",
  "    }",
  "    if (packet.type === 'session_updated') {",
  "      state.session = packet.payload;",
  "      renderSession();",
  "      return;",
  "    }",
  "    if (packet.type === 'transcript_updated') {",
  "      state.transcript = packet.payload?.items || [];",
  "      renderTranscript();",
  "      return;",
  "    }",
  "    if (packet.type === 'error' || packet.type === 'blocked') {",
  "      setStatus(packet.payload?.message || 'Blocked.');",
  "      return;",
  "    }",
  "    if (packet.type === 'queued') {",
  "      setStatus(`Prompt queued (${packet.payload?.queue_depth || 0}).`);",
  "      byId('prompt-input').value = '';",
  "      return;",
  "    }",
  "    if (packet.type === 'prompt_started') {",
  "      setStatus(`Prompt started: ${packet.payload?.prompt_id || ''}`);",
  "      return;",
  "    }",
  "    if (packet.type === 'prompt_completed') {",
  "      setStatus(packet.payload?.result?.text || 'Prompt completed.');",
  "      return;",
  "    }",
  "    if (packet.type === 'prompt_failed') {",
  "      setStatus(packet.payload?.error || 'Prompt failed.');",
  "    }",
  "  });",
  "  ws.addEventListener('close', () => {",
  "    state.connected = false;",
  "    renderSession();",
  "    setStatus('Disconnected.');",
  "  });",
  "}",
  "",
  "async function connect() {",
  "  state.token = byId('token-input').value.trim();",
  "  if (!state.token) {",
  "    setStatus('Token is required.');",
  "    return;",
  "  }",
  "  localStorage.setItem(tokenStorageKey(), state.token);",
  "  try {",
  "    await fetchJson('/api/chat/token/verify', { method: 'POST', body: JSON.stringify({ token: state.token }) });",
  "    await loadBootstrap();",
  "    connectWebSocket();",
  "  } catch (err) {",
  "    setStatus(err instanceof Error ? err.message : String(err));",
  "  }",
  "}",
  "",
  "function sendPrompt() {",
  "  const prompt = byId('prompt-input').value.trim();",
  "  if (!state.ws || state.ws.readyState !== WebSocket.OPEN) {",
  "    setStatus('Connect first.');",
  "    return;",
  "  }",
  "  if (!prompt) {",
  "    setStatus('Prompt cannot be empty.');",
  "    return;",
  "  }",
  "  state.ws.send(JSON.stringify({ type: 'submit_prompt', prompt }));",
  "}",
  "",
  "async function copyResumeCommand() {",
  "  const text = byId('manual-resume-command').textContent || '';",
  "  if (!text || text === 'No Codex session bound.') {",
  "    setStatus('No resume command available.');",
  "    return;",
  "  }",
  "  await copyText(text, 'Manual resume command copied.');",
  "}",
  "",
  "async function revealBoundSession(target) {",
  "  try {",
  "    const payload = await fetchJson('/api/chat/reveal', {",
  "      method: 'POST',",
  "      body: JSON.stringify({ target })",
  "    });",
  "    setStatus(`Revealed ${payload.target}: ${payload.path}`);",
  "  } catch (err) {",
  "    setStatus(err instanceof Error ? err.message : String(err));",
  "  }",
  "}",
  "",
  "window.addEventListener('DOMContentLoaded', async () => {",
  "  const params = new URLSearchParams(location.search);",
  "  const token = params.get('token') || localStorage.getItem(tokenStorageKey()) || '';",
  "  byId('token-input').value = token;",
  "  byId('connect-button').addEventListener('click', () => connect());",
  "  byId('disconnect-button').addEventListener('click', () => disconnect());",
  "  byId('send-button').addEventListener('click', () => sendPrompt());",
  "  byId('copy-resume-button').addEventListener('click', () => copyResumeCommand());",
  "  byId('copy-session-id-button').addEventListener('click', () => copyText(state.session?.bound_session?.session_id || '', 'Session ID copied.'));",
  "  byId('copy-session-path-button').addEventListener('click', () => copyText(state.session?.bound_session?.session_path || '', 'Session path copied.'));",
  "  byId('reveal-session-file-button').addEventListener('click', () => revealBoundSession('file'));",
  "  byId('reveal-session-folder-button').addEventListener('click', () => revealBoundSession('folder'));",
  "  byId('prompt-input').addEventListener('keydown', (event) => {",
  "    if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') {",
  "      sendPrompt();",
  "    }",
  "  });",
  "  if (token) {",
  "    await connect();",
  "  } else {",
  "    renderSession();",
  "    renderTranscript();",
  "  }",
  "});",
  ""
].join("\n");
