function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildRemoteHtml({ projectName }) {
  const safeProject = escapeHtml(projectName || "Kami Flow Remote");
  return [
    "<!doctype html>",
    "<html lang=\"en\">",
    "<head>",
    "  <meta charset=\"utf-8\">",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
    `  <title>${safeProject} - Remote</title>`,
    "  <link rel=\"stylesheet\" href=\"/assets/remote.css\">",
    "</head>",
    "<body>",
    "  <div class=\"app\">",
    "    <header class=\"topbar\">",
    `      <div><p class=\"eyebrow\">Kami Flow Remote</p><h1>${safeProject}</h1></div>`,
    "      <div class=\"status-row\">",
    "        <span id=\"connection-badge\" class=\"badge\">Disconnected</span>",
    "        <span id=\"busy-badge\" class=\"badge badge-muted\">Idle</span>",
    "      </div>",
    "    </header>",
    "",
    "    <section class=\"card auth-card\" id=\"auth-card\">",
    "      <label class=\"field\">",
    "        <span>Access Token</span>",
    "        <input id=\"token-input\" type=\"password\" placeholder=\"Paste the remote token\">",
    "      </label>",
    "      <div class=\"auth-actions\">",
    "        <button id=\"connect-button\" type=\"button\">Connect</button>",
    "        <button id=\"forget-button\" type=\"button\" class=\"button-secondary\">Forget</button>",
    "      </div>",
    "      <p class=\"hint\">Use the token printed by <code>kfc remote serve</code> or stored via <code>kfc remote token show</code>.</p>",
    "    </section>",
    "",
    "    <main class=\"layout\">",
    "      <section class=\"card stack\">",
    "        <div class=\"section-head\">",
    "          <h2>Session</h2>",
    "          <span id=\"queue-label\" class=\"meta\">Queue 0</span>",
    "        </div>",
    "        <dl id=\"session-grid\" class=\"session-grid\"></dl>",
    "      </section>",
    "",
    "      <section class=\"card stack transcript-card\">",
    "        <div class=\"section-head\">",
    "          <h2>Transcript</h2>",
    "          <span id=\"transcript-count\" class=\"meta\">0 entries</span>",
    "        </div>",
    "        <div id=\"transcript-list\" class=\"transcript-list\"></div>",
    "      </section>",
    "",
    "      <section class=\"card stack\">",
    "        <div class=\"section-head\">",
    "          <h2>Prompt</h2>",
    "          <span id=\"prompt-state\" class=\"meta\">No bound session</span>",
    "        </div>",
    "        <label class=\"field\">",
    "          <span>Message</span>",
    "          <textarea id=\"prompt-input\" rows=\"5\" placeholder=\"Send the next prompt into the bound workstation session.\"></textarea>",
    "        </label>",
    "        <div class=\"auth-actions\">",
    "          <button id=\"send-button\" type=\"button\">Send Prompt</button>",
    "        </div>",
    "        <p id=\"prompt-hint\" class=\"hint\">The queue is serialized. If the workstation is busy, your prompt waits its turn.</p>",
    "      </section>",
    "    </main>",
    "  </div>",
    "",
    "  <script src=\"/assets/remote.js\"></script>",
    "</body>",
    "</html>"
  ].join("\n");
}

export const REMOTE_UI_CSS = [
  ":root {",
  "  color-scheme: dark;",
  "  --bg: #0f141c;",
  "  --panel: #16202b;",
  "  --panel-2: #1b2734;",
  "  --border: #2f4359;",
  "  --text: #edf3fb;",
  "  --muted: #9ab0c7;",
  "  --accent: #4fc3f7;",
  "  --good: #66bb6a;",
  "  --warn: #ffca57;",
  "  --bad: #ef5350;",
  "  --shadow: rgba(0, 0, 0, 0.28);",
  "  font-family: \"Segoe UI\", system-ui, sans-serif;",
  "}",
  "body { margin: 0; background: radial-gradient(circle at top, #162536, var(--bg) 48%); color: var(--text); }",
  ".app { max-width: 960px; margin: 0 auto; padding: 20px 16px 40px; }",
  ".topbar { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; margin-bottom: 16px; }",
  ".eyebrow { margin: 0 0 4px; color: var(--muted); font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; }",
  "h1, h2 { margin: 0; }",
  ".layout { display: grid; gap: 16px; }",
  ".card { background: color-mix(in srgb, var(--panel) 92%, transparent); border: 1px solid var(--border); border-radius: 18px; box-shadow: 0 16px 42px var(--shadow); padding: 16px; }",
  ".stack { display: grid; gap: 12px; }",
  ".section-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; }",
  ".status-row, .auth-actions { display: flex; gap: 8px; flex-wrap: wrap; }",
  ".badge { border-radius: 999px; padding: 6px 10px; border: 1px solid var(--border); background: var(--panel-2); font-size: 12px; }",
  ".badge-ok { border-color: color-mix(in srgb, var(--good) 40%, var(--border)); color: var(--good); }",
  ".badge-busy { border-color: color-mix(in srgb, var(--accent) 40%, var(--border)); color: var(--accent); }",
  ".badge-blocked { border-color: color-mix(in srgb, var(--bad) 40%, var(--border)); color: var(--bad); }",
  ".badge-muted { color: var(--muted); }",
  ".field { display: grid; gap: 8px; font-size: 14px; }",
  ".field span { color: var(--muted); }",
  "input, textarea, button { font: inherit; }",
  "input, textarea { width: 100%; box-sizing: border-box; border-radius: 12px; border: 1px solid var(--border); background: #0d1722; color: var(--text); padding: 12px; }",
  "textarea { resize: vertical; min-height: 120px; }",
  "button { border: 1px solid color-mix(in srgb, var(--accent) 55%, var(--border)); background: color-mix(in srgb, var(--accent) 18%, #0d1722); color: var(--text); padding: 12px 14px; border-radius: 12px; }",
  "button:disabled { opacity: 0.6; }",
  ".button-secondary { border-color: var(--border); background: var(--panel-2); }",
  ".hint, .meta { color: var(--muted); font-size: 13px; margin: 0; }",
  ".session-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; margin: 0; }",
  ".session-grid div { background: rgba(0, 0, 0, 0.14); border-radius: 14px; padding: 12px; }",
  ".session-grid dt { color: var(--muted); font-size: 12px; margin-bottom: 6px; }",
  ".session-grid dd { margin: 0; font-size: 14px; word-break: break-word; }",
  ".transcript-list { display: grid; gap: 10px; max-height: 52vh; overflow: auto; }",
  ".transcript-entry { border: 1px solid var(--border); border-radius: 14px; padding: 12px; background: rgba(8, 15, 24, 0.48); }",
  ".transcript-entry-user { border-color: color-mix(in srgb, var(--accent) 24%, var(--border)); }",
  ".transcript-entry-assistant { border-color: color-mix(in srgb, var(--good) 24%, var(--border)); }",
  ".transcript-entry-system { border-color: color-mix(in srgb, var(--warn) 24%, var(--border)); }",
  ".transcript-meta { display: flex; justify-content: space-between; gap: 8px; margin-bottom: 8px; color: var(--muted); font-size: 12px; }",
  ".transcript-text { white-space: pre-wrap; word-break: break-word; line-height: 1.5; }",
  "code { background: rgba(255,255,255,0.06); border: 1px solid var(--border); border-radius: 8px; padding: 2px 6px; }",
  "@media (max-width: 720px) {",
  "  .topbar { flex-direction: column; }",
  "  .session-grid { grid-template-columns: 1fr; }",
  "  .app { padding-left: 12px; padding-right: 12px; }",
  "}",
  ""
].join("\n");

export const REMOTE_UI_JS = [
  "const TOKEN_KEY = 'kfc.remote.token';",
  "const byId = (id) => document.getElementById(id);",
  "const state = { token: '', session: null, transcript: [], eventSource: null };",
  "",
  "function readTokenFromUrl() {",
  "  const params = new URLSearchParams(window.location.search);",
  "  return (params.get('token') || '').trim();",
  "}",
  "",
  "function readStoredToken() {",
  "  return window.localStorage.getItem(TOKEN_KEY) || '';",
  "}",
  "",
  "function saveToken(token) {",
  "  state.token = token;",
  "  if (token) {",
  "    window.localStorage.setItem(TOKEN_KEY, token);",
  "  } else {",
  "    window.localStorage.removeItem(TOKEN_KEY);",
  "  }",
  "  byId('token-input').value = token;",
  "}",
  "",
  "function authHeaders() {",
  "  return state.token ? { Authorization: `Bearer ${state.token}` } : {};",
  "}",
  "",
  "function setConnection(text, cls) {",
  "  const badge = byId('connection-badge');",
  "  badge.textContent = text;",
  "  badge.className = `badge ${cls || ''}`.trim();",
  "}",
  "",
  "function setBusy(text, cls) {",
  "  const badge = byId('busy-badge');",
  "  badge.textContent = text;",
  "  badge.className = `badge ${cls || 'badge-muted'}`.trim();",
  "}",
  "",
  "function escapeHtml(value) {",
  "  return String(value || '')",
  "    .replace(/&/g, '&amp;')",
  "    .replace(/</g, '&lt;')",
  "    .replace(/>/g, '&gt;')",
  "    .replace(/\"/g, '&quot;');",
  "}",
  "",
  "function renderSession() {",
  "  const session = state.session || {};",
  "  const bound = session.bound_session || { bound: false, reason: 'No bound session.' };",
  "  const items = [",
  "    ['State', session.status || 'idle'],",
  "    ['Plan', bound.plan_id || 'None'],",
  "    ['Queue', String(session.queue_depth || 0)],",
  "    ['Run State', bound.runlog?.run_state || 'Unknown'],",
  "    ['Phase', bound.runlog?.phase || 'Unknown'],",
  "    ['Last Result', session.last_result?.state || 'None'],",
  "    ['Reason', bound.bound ? (session.last_result?.text || 'Ready') : bound.reason || 'No bound session']",
  "  ];",
  "  byId('session-grid').innerHTML = items.map(([label, value]) => `<div><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd></div>`).join('');",
  "  byId('queue-label').textContent = `Queue ${session.queue_depth || 0}`;",
  "  const busy = Boolean(session.busy);",
  "  setBusy(busy ? 'Working' : (session.status === 'blocked' ? 'Blocked' : 'Idle'), busy ? 'badge badge-busy' : (session.status === 'blocked' ? 'badge badge-blocked' : 'badge badge-muted'));",
  "  byId('prompt-state').textContent = bound.bound ? (busy ? 'Busy: prompt queued' : 'Ready to send') : 'No bound session';",
  "  byId('send-button').disabled = !bound.bound || !state.token;",
  "}",
  "",
  "function renderTranscript() {",
  "  const entries = Array.isArray(state.transcript) ? state.transcript : [];",
  "  byId('transcript-count').textContent = `${entries.length} entries`;",
  "  byId('transcript-list').innerHTML = entries.map((entry) => {",
  "    const role = entry.role || 'system';",
  "    const created = entry.created_at ? new Date(entry.created_at).toLocaleString() : '';",
  "    return `<article class=\"transcript-entry transcript-entry-${escapeHtml(role)}\"><div class=\"transcript-meta\"><strong>${escapeHtml(role)}</strong><span>${escapeHtml(created)}</span></div><div class=\"transcript-text\">${escapeHtml(entry.text || '')}</div></article>`;",
  "  }).join('');",
  "}",
  "",
  "async function fetchJson(url, options = {}) {",
  "  const response = await fetch(url, { ...options, headers: { ...(options.headers || {}), ...authHeaders(), 'Content-Type': 'application/json' } });",
  "  const text = await response.text();",
  "  let payload = {};",
  "  try { payload = text ? JSON.parse(text) : {}; } catch { payload = { error: text || 'Invalid JSON response.' }; }",
  "  if (!response.ok) {",
  "    throw new Error(payload.error || `Request failed (${response.status})`);",
  "  }",
  "  return payload;",
  "}",
  "",
  "async function loadSnapshot() {",
  "  state.session = await fetchJson('/api/remote/session');",
  "  const transcriptPayload = await fetchJson('/api/remote/transcript');",
  "  state.transcript = transcriptPayload.items || [];",
  "  renderSession();",
  "  renderTranscript();",
  "}",
  "",
  "function handleEventMessage(event) {",
  "  let payload = {};",
  "  try { payload = event.data ? JSON.parse(event.data) : {}; } catch { return; }",
  "  if (event.type === 'session_updated' || payload.event_type === 'session_updated') {",
  "    state.session = payload.session || state.session;",
  "    renderSession();",
  "    return;",
  "  }",
  "  if (event.type === 'transcript_appended' || payload.event_type === 'transcript_appended') {",
  "    if (payload.entry) {",
  "      state.transcript = [...state.transcript, payload.entry].slice(-200);",
  "      renderTranscript();",
  "    }",
  "  }",
  "}",
  "",
  "function closeEvents() {",
  "  if (state.eventSource) {",
  "    state.eventSource.close();",
  "    state.eventSource = null;",
  "  }",
  "}",
  "",
  "function openEvents() {",
  "  closeEvents();",
  "  const token = encodeURIComponent(state.token);",
  "  const source = new EventSource(`/api/remote/events?token=${token}`);",
  "  source.addEventListener('open', () => setConnection('Connected', 'badge badge-ok'));",
  "  source.addEventListener('error', () => setConnection('Reconnect needed', 'badge badge-blocked'));",
  "  source.addEventListener('connected', handleEventMessage);",
  "  source.addEventListener('session_updated', handleEventMessage);",
  "  source.addEventListener('transcript_appended', handleEventMessage);",
  "  state.eventSource = source;",
  "}",
  "",
  "async function connect() {",
  "  const token = String(byId('token-input').value || '').trim();",
  "  if (!token) {",
  "    setConnection('Token required', 'badge badge-blocked');",
  "    return;",
  "  }",
  "  saveToken(token);",
  "  try {",
  "    await fetchJson('/api/remote/token/verify', { method: 'POST', body: JSON.stringify({ token }) });",
  "    await loadSnapshot();",
  "    openEvents();",
  "    setConnection('Connected', 'badge badge-ok');",
  "  } catch (err) {",
  "    setConnection(err instanceof Error ? err.message : String(err), 'badge badge-blocked');",
  "  }",
  "}",
  "",
  "async function sendPrompt() {",
  "  const prompt = String(byId('prompt-input').value || '').trim();",
  "  if (!prompt) return;",
  "  byId('send-button').disabled = true;",
  "  try {",
  "    await fetchJson('/api/remote/prompt', { method: 'POST', body: JSON.stringify({ prompt }) });",
  "    byId('prompt-input').value = '';",
  "  } catch (err) {",
  "    window.alert(err instanceof Error ? err.message : String(err));",
  "  } finally {",
  "    renderSession();",
  "  }",
  "}",
  "",
  "function forgetToken() {",
  "  saveToken('');",
  "  closeEvents();",
  "  setConnection('Disconnected', 'badge');",
  "  byId('send-button').disabled = true;",
  "}",
  "",
  "window.addEventListener('DOMContentLoaded', async () => {",
  "  saveToken(readTokenFromUrl() || readStoredToken());",
  "  byId('connect-button').addEventListener('click', connect);",
  "  byId('forget-button').addEventListener('click', forgetToken);",
  "  byId('send-button').addEventListener('click', sendPrompt);",
  "  if (state.token) {",
  "    await connect();",
  "  } else {",
  "    renderSession();",
  "    renderTranscript();",
  "  }",
  "});",
  ""
].join("\n");
