import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CANDIDATE_ROOTS = [
  path.resolve(__dirname, "../../.."),
  path.resolve(__dirname, "../.."),
  process.cwd(),
  path.resolve(process.cwd(), "..")
];

function resolveRepoRootDir(startDirs = CANDIDATE_ROOTS) {
  for (const candidate of startDirs) {
    const basePath = path.join(candidate, "resources", "rules", "base.rules");
    const packagePath = path.join(candidate, "package.json");
    if (fs.existsSync(basePath) && fs.existsSync(packagePath)) {
      return candidate;
    }
  }
  return path.resolve(process.cwd());
}

const ROOT_DIR = resolveRepoRootDir();

export const RULES_FILE_NAME = "kamiflow.rules";
export const DEFAULT_RULES_PROFILE = "client";
export const VALID_RULES_PROFILES = ["dogfood", "client"];

export function getRepoRootDir() {
  return ROOT_DIR;
}

export function getBaseRulesSource(rootDir = ROOT_DIR) {
  return path.join(rootDir, "resources", "rules", "base.rules");
}

export function getProfileRulesSource(profileName, rootDir = ROOT_DIR) {
  return path.join(rootDir, "resources", "rules", "profiles", `${profileName}.rules`);
}

export function validateRulesProfile(profileName, sourceLabel = "input") {
  if (!VALID_RULES_PROFILES.includes(profileName)) {
    throw new Error(
      `Invalid rules profile from ${sourceLabel}: ${profileName}. Use one of: ${VALID_RULES_PROFILES.join(", ")}.`
    );
  }
  return profileName;
}

export function readRulesProfileFromProjectConfig(projectDir) {
  const configPath = path.join(projectDir, "kamiflow.config.json");
  if (!fs.existsSync(configPath)) {
    return "";
  }

  const raw = fs.readFileSync(configPath, "utf8");
  const parsed = JSON.parse(raw);
  const profile = parsed?.codex?.rulesProfile;
  if (profile === undefined) {
    return "";
  }
  if (typeof profile !== "string" || profile.trim().length === 0) {
    throw new Error(`Invalid codex.rulesProfile in ${configPath}: expected non-empty string.`);
  }

  return validateRulesProfile(profile.trim(), configPath);
}

export function composeRulesForProfile(profileName, rootDir = ROOT_DIR) {
  const normalizedProfile = validateRulesProfile(profileName, "compose");
  const basePath = getBaseRulesSource(rootDir);
  const overlayPath = getProfileRulesSource(normalizedProfile, rootDir);

  if (!fs.existsSync(basePath)) {
    throw new Error(`Missing base rules file: ${basePath}`);
  }

  if (!fs.existsSync(overlayPath)) {
    throw new Error(`Missing profile rules file: ${overlayPath}`);
  }

  const baseText = fs.readFileSync(basePath, "utf8").replace(/^\uFEFF/, "").trimEnd();
  const overlayText = fs.readFileSync(overlayPath, "utf8").replace(/^\uFEFF/, "").trimEnd();
  return [baseText, overlayText].filter(Boolean).join("\n\n") + "\n";
}

export function buildManagedRulesContent({
  profileName,
  sourceRulesText,
  generatedBy,
  generatedAt = new Date().toISOString(),
  rootDir = ROOT_DIR
}) {
  const normalizedProfile = validateRulesProfile(profileName, "buildManagedRulesContent");
  const basePath = getBaseRulesSource(rootDir);
  const overlayPath = getProfileRulesSource(normalizedProfile, rootDir);
  const generatedByLabel = generatedBy || "unknown-generator";

  const sources = [
    path.relative(rootDir, basePath).split(path.sep).join("/"),
    path.relative(rootDir, overlayPath).split(path.sep).join("/")
  ];

  const header = [
    `# Generated by ${generatedByLabel}`,
    `# Profile: ${normalizedProfile}`,
    `# Source: ${sources.join(" + ")}`,
    `# Generated at (UTC): ${generatedAt}`,
    "# DO NOT EDIT THIS FILE DIRECTLY.",
    "# Edit resources/rules/base.rules and resources/rules/profiles/*.rules, then run npm run codex:sync -- --only rules --force.",
    ""
  ].join("\n");

  return `${header}\n${String(sourceRulesText || "").replace(/^\uFEFF/, "")}`;
}

export function normalizeManagedRulesContent(contentText) {
  return String(contentText || "")
    .replace(/^\uFEFF/, "")
    .replace(/^# Generated by .*$/m, "# Generated by <normalized>")
    .replace(/^# Generated at \(UTC\):.*$/m, "# Generated at (UTC): <normalized>")
    .trimEnd();
}
