function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildHtml({ sessionsRoot }) {
  const safeRoot = escapeHtml(sessionsRoot);
  return [
    "<!doctype html>",
    "<html lang=\"en\">",
    "<head>",
    "  <meta charset=\"utf-8\">",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
    "  <title>KFCS</title>",
    "  <link rel=\"stylesheet\" href=\"/assets/kfcs.css\">",
    "</head>",
    "<body>",
    "  <div class=\"app-shell\">",
    "    <header class=\"hero\">",
    "      <div>",
    "        <p class=\"eyebrow\">KFCS</p>",
    "        <h1>Codex Session Manager</h1>",
    "        <p class=\"lede\">Browse, inspect, export, import, and restore Codex sessions without touching KFC workflow controls.</p>",
    "      </div>",
    `      <div class=\"hero-meta\"><span class=\"meta-chip\">Sessions Root</span><code>${safeRoot}</code></div>`,
    "    </header>",
    "",
    "    <main class=\"workspace\">",
    "      <section class=\"panel panel-list\">",
    "        <div class=\"panel-head\">",
    "          <div>",
    "            <p class=\"panel-kicker\">Session Browser</p>",
    "            <h2>Sessions</h2>",
    "          </div>",
    "          <span id=\"session-count\" class=\"meta-chip\">0 sessions</span>",
    "        </div>",
    "        <div class=\"toolbar\">",
    "          <label class=\"field\">",
    "            <span>Search</span>",
    "            <input id=\"search-input\" type=\"search\" placeholder=\"Session id, file, preview\">",
    "          </label>",
    "          <label class=\"field field-date\">",
    "            <span>Date</span>",
    "            <input id=\"date-input\" type=\"text\" placeholder=\"YYYY/MM/DD\">",
    "          </label>",
    "          <button id=\"refresh-button\" type=\"button\">Refresh</button>",
    "        </div>",
    "        <div id=\"session-list\" class=\"session-list\"></div>",
    "      </section>",
    "",
    "      <section class=\"panel panel-detail\">",
    "        <div class=\"panel-head\">",
    "          <div>",
    "            <p class=\"panel-kicker\">Session Detail</p>",
    "            <h2 id=\"detail-title\">Select a session</h2>",
    "          </div>",
    "          <div class=\"detail-actions\">",
    "            <button id=\"copy-id-button\" type=\"button\" class=\"button-secondary\" disabled>Copy ID</button>",
    "            <button id=\"copy-path-button\" type=\"button\" class=\"button-secondary\" disabled>Copy Path</button>",
    "          </div>",
    "        </div>",
    "        <dl id=\"detail-grid\" class=\"detail-grid\"></dl>",
    "        <section class=\"action-card\">",
    "          <h3>Export</h3>",
    "          <label class=\"field\">",
    "            <span>Destination Path</span>",
    "            <input id=\"export-path-input\" type=\"text\" placeholder=\"E:/transfer/codex-sessions\">",
    "          </label>",
    "          <button id=\"export-button\" type=\"button\" disabled>Export Session</button>",
    "        </section>",
    "        <section class=\"action-card\">",
    "          <h3>Import</h3>",
    "          <label class=\"field\">",
    "            <span>Source Path</span>",
    "            <input id=\"import-path-input\" type=\"text\" placeholder=\"E:/transfer/codex-sessions/2026/03/07/session.jsonl\">",
    "          </label>",
    "          <button id=\"import-button\" type=\"button\">Import Into Codex Sessions Root</button>",
    "        </section>",
    "        <section class=\"action-card\">",
    "          <h3>Restore</h3>",
    "          <p class=\"hint\">Restore confirms the session is present in the Codex sessions root and gives you the session id/path for manual resume.</p>",
    "          <button id=\"restore-button\" type=\"button\" disabled>Restore Session</button>",
    "        </section>",
    "        <section class=\"action-card action-card-preview\">",
    "          <div class=\"section-row\">",
    "            <h3>Transcript Tail</h3>",
    "            <span class=\"meta-chip\">latest lines</span>",
    "          </div>",
    "          <div id=\"detail-preview\" class=\"preview-list\"></div>",
    "          <pre id=\"detail-tail\" class=\"tail-view\"></pre>",
    "        </section>",
    "      </section>",
    "    </main>",
    "",
    "    <footer class=\"footer\">",
    "      <span id=\"status-line\">Ready.</span>",
    "    </footer>",
    "  </div>",
    "  <script src=\"/assets/kfcs.js\"></script>",
    "</body>",
    "</html>"
  ].join("\n");
}

export const KFCS_CSS = [
  ":root {",
  "  color-scheme: light dark;",
  "  --bg: #f4efe7;",
  "  --bg-accent: #efe4d4;",
  "  --panel: rgba(255, 250, 243, 0.9);",
  "  --border: rgba(100, 79, 48, 0.22);",
  "  --text: #24190f;",
  "  --muted: #6b5a47;",
  "  --accent: #116466;",
  "  --accent-soft: rgba(17, 100, 102, 0.12);",
  "  --highlight: #d97d54;",
  "  --shadow: rgba(73, 52, 30, 0.12);",
  "  font-family: \"Segoe UI Variable\", \"Aptos\", system-ui, sans-serif;",
  "}",
  "@media (prefers-color-scheme: dark) {",
  "  :root {",
  "    --bg: #10171f;",
  "    --bg-accent: #152331;",
  "    --panel: rgba(17, 24, 32, 0.92);",
  "    --border: rgba(150, 183, 206, 0.18);",
  "    --text: #edf5ff;",
  "    --muted: #9bb2c6;",
  "    --accent: #75c9d0;",
  "    --accent-soft: rgba(117, 201, 208, 0.14);",
  "    --highlight: #e4a46f;",
  "    --shadow: rgba(0, 0, 0, 0.28);",
  "  }",
  "}",
  "* { box-sizing: border-box; }",
  "body { margin: 0; background: radial-gradient(circle at top, var(--bg-accent), var(--bg) 46%); color: var(--text); }",
  "button, input { font: inherit; }",
  "code, pre { font-family: \"Cascadia Code\", \"Consolas\", monospace; }",
  ".app-shell { max-width: 1440px; margin: 0 auto; padding: 24px; display: grid; gap: 20px; }",
  ".hero { display: flex; align-items: flex-start; justify-content: space-between; gap: 20px; }",
  ".eyebrow, .panel-kicker { margin: 0 0 6px; color: var(--highlight); text-transform: uppercase; letter-spacing: 0.08em; font-size: 12px; font-weight: 700; }",
  ".hero h1, .panel-head h2, .action-card h3 { margin: 0; }",
  ".lede, .hint { color: var(--muted); max-width: 70ch; margin: 8px 0 0; }",
  ".hero-meta { display: grid; gap: 8px; justify-items: end; }",
  ".meta-chip { display: inline-flex; align-items: center; gap: 8px; border-radius: 999px; border: 1px solid var(--border); background: var(--accent-soft); color: var(--accent); padding: 6px 10px; font-size: 12px; font-weight: 600; }",
  ".workspace { display: grid; grid-template-columns: minmax(320px, 0.95fr) minmax(420px, 1.15fr); gap: 20px; }",
  ".panel, .action-card { background: var(--panel); border: 1px solid var(--border); border-radius: 24px; box-shadow: 0 16px 36px var(--shadow); }",
  ".panel { padding: 20px; display: grid; gap: 16px; min-height: 0; }",
  ".panel-head, .section-row { display: flex; align-items: center; justify-content: space-between; gap: 12px; }",
  ".toolbar { display: grid; grid-template-columns: minmax(0, 1fr) 180px auto; gap: 12px; align-items: end; }",
  ".field { display: grid; gap: 8px; }",
  ".field span { color: var(--muted); font-size: 13px; }",
  "input { border-radius: 14px; border: 1px solid var(--border); padding: 12px 14px; background: rgba(255,255,255,0.62); color: var(--text); }",
  "@media (prefers-color-scheme: dark) { input { background: rgba(0,0,0,0.18); } }",
  "button { border-radius: 14px; border: 1px solid color-mix(in srgb, var(--accent) 52%, var(--border)); background: color-mix(in srgb, var(--accent) 12%, transparent); color: var(--text); padding: 12px 14px; cursor: pointer; }",
  "button:disabled { opacity: 0.55; cursor: not-allowed; }",
  ".button-secondary { border-color: var(--border); background: transparent; }",
  ".session-list { display: grid; gap: 10px; max-height: 72vh; overflow: auto; padding-right: 4px; }",
  ".session-item { display: grid; gap: 8px; border: 1px solid var(--border); border-radius: 18px; background: rgba(255,255,255,0.35); padding: 14px; cursor: pointer; text-align: left; }",
  "@media (prefers-color-scheme: dark) { .session-item { background: rgba(255,255,255,0.03); } }",
  ".session-item[data-selected=\"true\"] { border-color: color-mix(in srgb, var(--accent) 60%, var(--border)); box-shadow: 0 0 0 2px color-mix(in srgb, var(--accent) 18%, transparent); }",
  ".session-item-header { display: flex; justify-content: space-between; gap: 12px; align-items: center; }",
  ".session-id { font-weight: 700; }",
  ".session-meta, .session-preview { color: var(--muted); font-size: 13px; }",
  ".panel-detail { align-content: start; }",
  ".detail-actions { display: flex; gap: 8px; flex-wrap: wrap; }",
  ".detail-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; margin: 0; }",
  ".detail-grid div { border: 1px solid var(--border); border-radius: 18px; padding: 12px; background: rgba(255,255,255,0.28); }",
  "@media (prefers-color-scheme: dark) { .detail-grid div { background: rgba(255,255,255,0.04); } }",
  ".detail-grid dt { color: var(--muted); font-size: 12px; margin-bottom: 6px; }",
  ".detail-grid dd { margin: 0; word-break: break-word; }",
  ".action-card { padding: 16px; display: grid; gap: 12px; }",
  ".preview-list { display: grid; gap: 8px; }",
  ".preview-row { border-radius: 12px; border: 1px solid var(--border); padding: 10px 12px; background: rgba(255,255,255,0.2); }",
  "@media (prefers-color-scheme: dark) { .preview-row { background: rgba(255,255,255,0.03); } }",
  ".preview-role { color: var(--accent); font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }",
  ".preview-text { margin-top: 4px; }",
  ".tail-view { margin: 0; white-space: pre-wrap; background: rgba(0,0,0,0.06); border: 1px solid var(--border); border-radius: 16px; padding: 12px; max-height: 260px; overflow: auto; }",
  "@media (prefers-color-scheme: dark) { .tail-view { background: rgba(0,0,0,0.2); } }",
  ".footer { color: var(--muted); font-size: 14px; }",
  "@media (max-width: 1040px) { .workspace { grid-template-columns: 1fr; } .hero { flex-direction: column; } .hero-meta { justify-items: start; } }",
  "@media (max-width: 680px) { .toolbar { grid-template-columns: 1fr; } .detail-grid { grid-template-columns: 1fr; } .app-shell { padding: 16px; } }",
  ""
].join("\n");

export const KFCS_JS = [
  "const state = { sessions: [], selectedId: '', selected: null };",
  "const byId = (id) => document.getElementById(id);",
  "",
  "function escapeHtml(value) {",
  "  return String(value || '')",
  "    .replace(/&/g, '&amp;')",
  "    .replace(/</g, '&lt;')",
  "    .replace(/>/g, '&gt;')",
  "    .replace(/\"/g, '&quot;');",
  "}",
  "",
  "function setStatus(text) { byId('status-line').textContent = text; }",
  "",
  "async function fetchJson(url, options = {}) {",
  "  const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } });",
  "  const text = await response.text();",
  "  let payload = {};",
  "  try { payload = text ? JSON.parse(text) : {}; } catch { payload = { error: text || 'Invalid JSON response.' }; }",
  "  if (!response.ok) {",
  "    throw new Error(payload.error || `Request failed (${response.status})`);",
  "  }",
  "  return payload;",
  "}",
  "",
  "function renderSessions() {",
  "  byId('session-count').textContent = `${state.sessions.length} sessions`;",
  "  byId('session-list').innerHTML = state.sessions.map((session) => {",
  "    const selected = session.session_id === state.selectedId;",
  "    return `<button type=\"button\" class=\"session-item\" data-id=\"${escapeHtml(session.session_id)}\" data-selected=\"${selected}\"><div class=\"session-item-header\"><span class=\"session-id\">${escapeHtml(session.session_id)}</span><span class=\"meta-chip\">${escapeHtml(session.date_path || 'undated')}</span></div><div class=\"session-meta\">${escapeHtml(session.relative_path)}</div><div class=\"session-preview\">${escapeHtml(session.preview_text || 'No preview')}</div></button>`;",
  "  }).join('');",
  "  byId('session-list').querySelectorAll('[data-id]').forEach((button) => button.addEventListener('click', () => selectSession(button.dataset.id)));",
  "}",
  "",
  "function renderDetail() {",
  "  const selected = state.selected;",
  "  const disabled = !selected;",
  "  byId('copy-id-button').disabled = disabled;",
  "  byId('copy-path-button').disabled = disabled;",
  "  byId('export-button').disabled = disabled;",
  "  byId('restore-button').disabled = disabled;",
  "  if (!selected) {",
  "    byId('detail-title').textContent = 'Select a session';",
  "    byId('detail-grid').innerHTML = '';",
  "    byId('detail-preview').innerHTML = '';",
  "    byId('detail-tail').textContent = '';",
  "    return;",
  "  }",
  "  byId('detail-title').textContent = selected.session_id;",
  "  const items = [",
  "    ['File', selected.file_name],",
  "    ['Path', selected.file_path],",
  "    ['Modified', selected.modified_at],",
  "    ['Bytes', String(selected.bytes)],",
  "    ['Date', selected.date_path || 'undated'],",
  "    ['Relative', selected.relative_path]",
  "  ];",
  "  byId('detail-grid').innerHTML = items.map(([label, value]) => `<div><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd></div>`).join('');",
  "  byId('detail-preview').innerHTML = (selected.preview || []).map((item) => `<div class=\"preview-row\"><div class=\"preview-role\">${escapeHtml(item.role || 'event')}</div><div class=\"preview-text\">${escapeHtml(item.text || '')}</div></div>`).join('');",
  "  byId('detail-tail').textContent = selected.tail_text || '';",
  "}",
  "",
  "async function loadSessions() {",
  "  setStatus('Loading sessions…');",
  "  const search = encodeURIComponent(byId('search-input').value.trim());",
  "  const date = encodeURIComponent(byId('date-input').value.trim());",
  "  const payload = await fetchJson(`/api/sessions?query=${search}&date=${date}`);",
  "  state.sessions = payload.items || [];",
  "  if (!state.sessions.some((item) => item.session_id === state.selectedId)) {",
  "    state.selectedId = state.sessions[0]?.session_id || '';",
  "  }",
  "  renderSessions();",
  "  if (state.selectedId) {",
  "    await selectSession(state.selectedId, false);",
  "  } else {",
  "    state.selected = null;",
  "    renderDetail();",
  "  }",
  "  setStatus('Ready.');",
  "}",
  "",
  "async function selectSession(sessionId, setMessage = true) {",
  "  if (!sessionId) { return; }",
  "  state.selectedId = sessionId;",
  "  renderSessions();",
  "  const payload = await fetchJson(`/api/sessions/${encodeURIComponent(sessionId)}`);",
  "  state.selected = payload.item;",
  "  renderDetail();",
  "  if (setMessage) { setStatus(`Loaded ${sessionId}.`); }",
  "}",
  "",
  "async function runAction(label, url, body) {",
  "  setStatus(`${label}…`);",
  "  try {",
  "    const payload = await fetchJson(url, { method: 'POST', body: JSON.stringify(body) });",
  "    setStatus(payload.message || `${label} complete.`);",
  "    await loadSessions();",
  "  } catch (err) {",
  "    setStatus(err instanceof Error ? err.message : String(err));",
  "  }",
  "}",
  "",
  "async function copyText(value, label) {",
  "  if (!value) return;",
  "  try {",
  "    await navigator.clipboard.writeText(value);",
  "    setStatus(`${label} copied.`);",
  "  } catch (err) {",
  "    setStatus(err instanceof Error ? err.message : String(err));",
  "  }",
  "}",
  "",
  "window.addEventListener('DOMContentLoaded', async () => {",
  "  byId('refresh-button').addEventListener('click', () => loadSessions());",
  "  byId('search-input').addEventListener('input', () => loadSessions());",
  "  byId('date-input').addEventListener('change', () => loadSessions());",
  "  byId('copy-id-button').addEventListener('click', () => copyText(state.selected?.session_id, 'Session ID'));",
  "  byId('copy-path-button').addEventListener('click', () => copyText(state.selected?.file_path, 'Session path'));",
  "  byId('export-button').addEventListener('click', () => runAction('Export', '/api/sessions/export', { id: state.selected?.session_id, to: byId('export-path-input').value.trim() }));",
  "  byId('import-button').addEventListener('click', () => runAction('Import', '/api/sessions/import', { from: byId('import-path-input').value.trim() }));",
  "  byId('restore-button').addEventListener('click', () => runAction('Restore', '/api/sessions/restore', { id: state.selected?.session_id }));",
  "  await loadSessions();",
  "});",
  ""
].join("\n");
